# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :android
VERSION_FILE="version.txt"
INTERNAL_REPO_NAME = "AylaNetworks/common_sepia"

import_from_git(
  url: 'https://github.com/AylaNetworks/mobile_release_scripts',
  path: 'Util/Fastfile',
  branch: 'develop'
)

def set_version_string(version)
    vFile = get_version_file
    [vFile].each do |f|
        file_contents = File.read(f)
        file_contents.gsub!(/.*(Version: )(.*)/, "\\1#{version}")
        File.write(f, file_contents)
    end
end

def get_version_file
    file_name = `find .. -name #{VERSION_FILE}`
    if file_name.nil? or file_name.empty?
        puts "Can not find version file by command #{file_name}. Please double check path and file name"
        exit!
    else
        file_name=file_name.chomp
    end
end


def get_version_string
    vFile=get_version_file
    version_sentence = `cat #{vFile} | grep "Version: "`
    version_string = version_sentence.split(":").last
    version_string.strip
end
